api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from api.views import BookReviewViewSet  #BookReviewDetailAPIView, BookReviewListAPIView

app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewViewSet, basename='review')
urlpatterns = router.urls


'''urlpatterns = [
    path('reviews/', BookReviewListAPIView.as_view(), name='review-list'),
    path('reviews/<int:id>/', BookReviewDetailAPIView.as_view(), name='review-detail'),
]
'''

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page , name='landing_page'),
    path('home/', home_page, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),

    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'users'

urlpatterns = [
   path('register/', RegisterView.as_view(), name='register'),
   path('login/', LoginView.as_view(), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('profile/', ProfileView.as_view(), name='profile'),
   path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import FileExtensionValidator

class CustomUser(AbstractUser):
    profile_picture = models.ImageField(
                      default='default_profile_picture.jpg',
                      validators=[FileExtensionValidator(allowed_extensions=['jpg','png','jpeg','heic','heif','jfif'])]
                     )

users/forms.py
from django import forms
from django.core.mail import send_mail

from users.models import CustomUser

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()
    
        return user

'''class UserCreateForm(forms.Form):
    username = forms.CharField(max_length=150)
    email = forms.EmailField()
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    password = forms.CharField(max_length=128)

    def save(self):
        username = self.changed_data['username']
        first_name = self.changed_data['first_name']
        last_name = self.changed_data['last_name']
        email = self.changed_data['email']
        password = self.changed_data['password']
            
        user = CustomUser.objects.create(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email
        )
        user.set_password(password)
        user.save()

        return user'''

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')

class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=128)

users/views.py
from django.contrib import messages
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin

from users.forms import UserCreateForm, UserLoginForm, UserUpdateForm
from users.models import CustomUser

class RegisterView(View):

    def get(self, request):
        create_form = UserCreateForm()
        context = {
            'form': create_form
        }
        return render(request, 'users/register.html', context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request, 'users/register.html', context)

class LoginView(View):

    def get(self, request):
        login_form = UserLoginForm() #instance
        context = {
            'login_form': login_form
        }
        return render(request, 'users/login.html', context)
    
    def post(self, request):
        login_form = AuthenticationForm(data=request.POST) #instance
        context = {
            'login_form': login_form
        }
        
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You have successfully logged in.')
            return redirect('books:list')
        else:
            return render(request, 'users/login.html', context)

class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        context = {
            'user': request.user
        }
        return render(request, 'users/profile.html', context)
    
class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, 'You have successfully logged out.')
        return redirect('landing_page')
    
class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        context = {
            'form': user_update_form
        }
        return render(request, 'users/profile_edit.html', context)
    
    def post(self, request):
        user_update_form = UserUpdateForm(instance=request.user, data=request.POST, files=request.FILES)

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, 'You have successfully updated your profile.')

            return redirect('users:profile')
        
        return render(request, 'users/profile_edit.html', {'form': user_update_form})

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Login Page {% endblock %}

{% block content %}
    <h3>Login</h3>
    
    <div class="row">
        <div class="col-4">
            <form method="post">
                {% csrf_token %}
                {{login_form | crispy }}
                <button class="btn btn-primary">Log in</button> <span class="ms-3">No account? Then, <a href="{% url 'users:register' %}">get registered</a></span>
             </form>
        </div>
    </div>
   
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %} Profile Page {% endblock %}

{% block content %}
<h1>Profile Page</h1>
  
            <div class=" image d-flex flex-column justify-content-center align-items-center">
                <button class="btn btn-secondary"> 
                    <img class="profile-pic" src="{{ user.profile_picture.url }}" alt="Profile_picture"> 
                </button>
                <span class="name mt-3">{{ user.first_name }} {{ user.last_name }}</span>
                <span class="idd">@{{ user.username }}</span>
                <span class="idd">{{ user.email }}</span>
                <div class=" d-flex mt-2"> <a class="btn btn-dark" href="{% url 'users:profile-edit' %}">edit profile</a> </div>
                <div class=" px-2 rounded mt-4 date "> <span class="join">Joined {{ user.data_joined|date:"M d, Y"}}</span> </div>
            </div>
   
        <!--
            
            <div>
                
            </div>
        
            <p>Username: {{user.username}}</p>
            <p>First name: {{user.first_name}}</p>
            <p>Last_name:{{user.last_name}}</p>
            <p>Email: {{user.email}}</p>-->

{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Profile Edit{% endblock %}

{% block content %}
   <h3>Profile Edit</h3>
   <div class="row">
      <div class="col-4">
            <form method="post" enctype="multipart/form-data">
               {% csrf_token %}
      
               {{form | crispy }}
      
               <button class="btn btn-primary">Save Changes</button>
            </form>
      </div>
   </div>
 

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Register Page {% endblock %}
 
{% block content %}
    <h3>Register</h3>

    <div class="row">
        <div class="col-4">
            <form method="post" action="{% url 'users:register' %}"> 
                {% csrf_token %}
                {{form | crispy }}
        
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
   
{% endblock %}