api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from api.views import BookReviewViewSet  #BookReviewDetailAPIView, BookReviewListAPIView

app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewViewSet, basename='review')
urlpatterns = router.urls


'''urlpatterns = [
    path('reviews/', BookReviewListAPIView.as_view(), name='review-list'),
    path('reviews/<int:id>/', BookReviewDetailAPIView.as_view(), name='review-detail'),
]
'''

books/urls.py
from django.urls import path
from .views import BookView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView

app_name = 'books'

urlpatterns = [
    path('', BookView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path("<int:id>/reviews/", AddReviewView.as_view(), name='reviews'),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name='edit-review'),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm", ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name='delete-review')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page , name='landing_page'),
    path('home/', home_page, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),

    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'users'

urlpatterns = [
   path('register/', RegisterView.as_view(), name='register'),
   path('login/', LoginView.as_view(), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('profile/', ProfileView.as_view(), name='profile'),
   path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit')
]

templates/base.html
{% load static %}
{% url 'home_page' as home_url %}
{% url 'books:list' as books_url %}
{% url 'users:profile' as profile_url %}
{% url 'users:profile-edit' as profile_edit_url %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>{% block title %} Goodread {% endblock %}</title>
</head>

<body class="mx-5">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home_url %} active {% endif %}" aria-current="page" href="{{home_url}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == books_url %} active {% endif %}" aria-current="page" href="{{books_url}}">Books</a>
                    </li>
                </ul>
                <div class="me-5">
                    {% if request.user.is_authenticated %}
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle {% if request.path == profile_url or request.path == profile_edit_url %} active {% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ request.user.username }}
                                </a>
                                <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{{profile_url}}">Profile</a></li>
                                <li><a class="dropdown-item" href="#"></a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                                </ul>
                            </li>
                        </ul>  
                    {% else %}
                        <a class="btn btn-primary" href="{% url 'users:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
  
    <div class="container">
        {% if messages %}
        <div class="mt-3">
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}" role="alert">
                    {{message}}
                </div>
            {% endfor %}
        </div>
      
        {% endif %}
    
        {% block content %}

        {% endblock %}

    </div>

  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}


{% block title %} Home Page {% endblock %}

{% block content %}
   <h1>All Reviews</h1>

   {% for review in page_obj %}
      <div class="container posts-content">
         <div class="row">
            <div class="col-lg-6">
               <div class="card mb-4">
                  <div class="card-body">
                     <div class="media mb-3">
                     <img src="{{ review.user.profile_picture.url }}" class="d-block ui-w-40 rounded-circle" alt="">
                     <div class="media-body ml-3">
                        <b>{{ review.user.username }} rated this book {{ review.stars_given }} stars </b> 
                        <div class="text-muted small">{{ review.created_at|date:"M d, Y"}}</div>
                     </div>
                     </div>
                     <p>
                     {{ review.comment|truncatechars:300 }}
                     </p>
                     <img class="cover-pic center" src="{{ review.book.cover_picture.url }}" alt="">
                  </div>
               </div>
            </div>
         </div>
      </div>
      

   {% endfor %}
   <nav>
      <ul class="pagination">
         {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
            <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">previous</a></li>
         {% endif %}
         
         <li class="page-item active">
               <a href="#" class="page-link">{{page_obj.number}}</a>
         </li>
         
         {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{page_obj.paginator.num_pages}}">last&raquo;</a></li>
         {% endif %}
      </ul>
   </nav>

{% endblock %}

templates/landing.html
{% extends 'base.html' %}

{% block content %}
    <h1>Landing Page</h1>
    <div class="p-5 mb-4 bg-light rounded-3 mx-5">
        <div class="container-fluid py-5">
          <h1 class="display-5 fw-bold">Custom jumbotron</h1>
          <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
          <button class="btn btn-primary btn-lg" type="button">Example button</button>
        </div>
    </div>
    <p>
        Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.[2]
        Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5] and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.[9]
        By July 2019, the site had 90 million members.[10]
    </p>
{% endblock %}